print("Testing...")
import time
time.sleep(2)
print("Testing...")
time.sleep(3)
import random
x = random.randint(1, 100)
y = random.randint(1, 100)
z = random.randint(1, 100)
sum = x + y + z
print("The Sum of", x,"and", y,"and", z, "is", sum)
print("Next")
time.sleep(3)
x = random.randint(1, 100)
y = random.randint(1, 100)
z = random.randint(1, 100)
sum = x + y + z
print("The Sum of", x,"and", y,"and", z, "is", sum)
print("Next")
time.sleep(3)
x = random.randint(1, 100)
y = random.randint(1, 100)
z = random.randint(1, 100)
sum = x + y + z
print("The Sum of", x,"and", y,"and", z,"is", sum)
print("Next")
time.sleep(3)
x = random.randint(1, 100)
y = random.randint(1, 100)
z = random.randint(1, 100)
sum = x + y + z
print("The Sum of", x,"and", y,"and", z,"is", sum)
print("Next")
time.sleep(3)
x = random.randint(1, 100)
y = random.randint(1, 100)
z = random.randint(1, 100)
sum = x + y + z
print("The Sum of", x,"and", y,"and", z,"is", sum)
print("Next")
time.sleep(3)
x = random.randint(1, 100)
y = random.randint(1, 100)
z = random.randint(1, 100)
sum = x + y + z
print("The Sum of", x,"and", y,"and", z,"is", sum)
time.sleep(3)
x = random.randint(1, 100)
y = random.randint(1, 100)
z = random.randint(1, 100)
sum = x + y + z
print("The Sum of", x,"and", y,"and", z,"is", sum)
print("Next")
time.sleep(3)
x = random.randint(1, 100)
y = random.randint(1, 100)
z = random.randint(1, 100)
sum = x + y + z
print("The Sum of", x,"and", y,"and", z,"is", sum)
print("Next")
time.sleep(3)
print("Now it's your turn for choosing the numbers!")
time.sleep(3)
x = int(input("Enter the first number: "))
y = int(input("Enter the second number: "))
z = int(input("Enter the third number: "))

sum = x + y + z
print("The sum of", x, "and", y, "and", z, "is", sum)
print("Next")
time.sleep(1)
x = int(input("Enter the first number:"))
y = int(input("Enter the second number:"))
z = int(input("Enter the third number:"))
sum = x + y + z
print("The sum of", x, "and", y,"and", z,"is", sum)
print("Next")
time.sleep(1)
x = int(input("Enter the first number:"))
y = int(input("Enter the second number:"))
z = int(input("Enter the third number:"))
sum = x + y + z
print("The sum of", x,"and", y,"and", z,"is", sum)
print("Next")
time.sleep(1)
x = int(input("Enter the first number:"))
y = int(input("Enter the second number:"))
z = int(input("Enter the third number:"))
sum = x + y + z
print("The sum of", x,"and", y,"and", z,"is", sum)
print("that's it")
time.sleep(6) #End of the code, made by FireShark224.